name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - name: where dotnet
        run: where dotnet
      - name: where msbuild
        run: where msbuild
