name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch,push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - name: Install Master Packager Dev
        run: |
          winget install --id=MasterPackager.MasterPackagerDev -e --accept-source-agreements --accept-package-agreements --skip-dependencies
          
