name: Create Release with Assets
on:
  push:
    tags:
      - "v*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Verify tag
        if: github.ref_type != 'tag'
        run: |
          echo "::error::This workflow must run from a Git tag."
          exit 1

      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Get release version vX.X
        id: version
        run: |
          $vXX = '${{ github.ref_name }}' -replace '\.\d+$', ''
          "vXX=$vXX" >> $env:GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          body: |
            [What's new in ${{ steps.version.outputs.vXX }}](https://github.com/qgindi/LibreAutomate/blob/master/Other/DocFX/_doc/changes/${{ steps.version.outputs.vXX }}.md)

            ---

            Download and run `LibreAutomate.msi`.

            Or run [msiexec](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/msiexec). Examples:
            - Run the installer in reduced UI mode: `msiexec /i "msi file path" /qr`
            - Change the app folder: `msiexec /i "msi file path" INSTALLDIR="app folder path"`

            LibreAutomate uses the .NET 10 Desktop Runtime. Will prompt to install it if missing.

            Runs on Windows 10 (x64) and 11 (x64, Arm64). Also 7 and 8.1; see [installing .NET](https://learn.microsoft.com/en-us/dotnet/core/install/windows).

          files: bin\Release\net10.0\GitHub-actions.dll
