name: Create Release with Assets
on:
  push:
    tags:
      - "v*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        #if: github.ref_type == 'tag'
        with:
          files: bin\Release\net10.0\GitHub-actions.dll
